package execpolicy

import (
	"errors"
	"fmt"
	"strings"
)

// GeneratedServerEnv carries Council-generated transport credentials for an
// `opencode serve` child. It is NOT inherited environment: the values are
// generated by Council for this launch, injected verbatim after
// allowlist/scrub processing (so the secret filter cannot strip them), and
// must never appear in the frozen canonical profile.
//
// The executor accepts GeneratedServerEnv only when the launch shape is
// exactly `opencode serve` (validated in Start) — the caller's
// characterization of its purpose is never trusted.
type GeneratedServerEnv struct {
	Username string
	Password string
}

// ErrServerEnvShape reports GeneratedServerEnv on a launch that is not an
// `opencode serve` child.
var ErrServerEnvShape = errors.New("GeneratedServerEnv is only permitted on `opencode serve` launches")

// ErrServerEnvKeyCollision reports a collision between a GeneratedServerEnv
// key and an inherited or allowlisted environment key.
var ErrServerEnvKeyCollision = errors.New("GeneratedServerEnv key collides with an inherited or allowlisted environment key")

// isOpenCodeServeLaunch reports whether the request launches an
// `opencode serve` child (command base `opencode`, first arg `serve`).
func IsOpenCodeServeLaunch(req LaunchRequest) bool {
	cmdBase := req.Command
	if idx := strings.LastIndex(cmdBase, "/"); idx != -1 {
		cmdBase = cmdBase[idx+1:]
	}
	return cmdBase == "opencode" && len(req.Args) > 0 && req.Args[0] == "serve"
}

// validateGeneratedServerEnvShape enforces that GeneratedServerEnv appears
// only on an `opencode serve` launch.
func validateGeneratedServerEnvShape(req LaunchRequest) error {
	if req.GeneratedServerEnv == nil {
		return nil
	}
	if !IsOpenCodeServeLaunch(req) {
		return fmt.Errorf("%w: launch is %q %v", ErrServerEnvShape, req.Command, req.Args)
	}
	return nil
}

// validateGeneratedServerEnvCollisions rejects collisions between the
// GeneratedServerEnv keys and the allowlisted inherited-env keys.
func validateGeneratedServerEnvCollisions(req LaunchRequest, allowlisted map[string]struct{}) error {
	if req.GeneratedServerEnv == nil {
		return nil
	}
	for _, key := range []string{"OPENCODE_SERVER_USERNAME", "OPENCODE_SERVER_PASSWORD"} {
		if _, ok := allowlisted[key]; ok {
			return fmt.Errorf("%w: %q is allowlisted in the canonical profile", errServerEnvKeyCollision, key)
		}
	}
	return nil
}

// appendGeneratedServerEnv injects the two credential vars after the scrub
// pass, so the secret filter cannot strip them. Values were generated by
// Council for this launch and are redacted from all captured output
// elsewhere.
func appendGeneratedServerEnv(env []string, req LaunchRequest) []string {
	if req.GeneratedServerEnv == nil {
		return env
	}
	return append(env,
		"OPENCODE_SERVER_USERNAME="+req.GeneratedServerEnv.Username,
		"OPENCODE_SERVER_PASSWORD="+req.GeneratedServerEnv.Password,
	)
}

var errServerEnvKeyCollision = ErrServerEnvKeyCollision
